### ISSUE TITLE
Cannot change scope time per division

### ISSUE THREAD

**Issue by RamPawar7** [VoltSim/VoltSim#16]
In the latest update (0.1.12), the ability to change the time per division of the scope by swiping horizontally on it is not working.

**Comment by voltsimapp** [comment]
The old implementation was buggy as it didn't respect already existing data. With the new re-written scope, this functionality is split between scope zooming and sampling rate changing and is moved into scope extension. 

This would be moved out of the scope extension along with the ability to clear all plots in a future update.
