### ISSUE TITLE
Mosfet issue 

### ISSUE THREAD

**Issue by fondbcn** [VoltSim/VoltSim#18]
The id current is false in the parameters, for example i have selecting a 1ohm with 20v that almost 20a but it shows a wrong value.
![Screenshot_2022-08-23-06-49-51-70](https://user-images.githubusercontent.com/111845235/186081822-f4c3d6c5-7460-4550-b881-bd9ec413e1e0.jpg)

**Comment by voltsimapp** [comment]
This has been fixed in the latest update, where an option to enable/disable body-diode was added.
