### ISSUE TITLE
Cant put components

### ISSUE THREAD

**Issue by MrAresCro** [VoltSim/VoltSim#19]
I cant put any components in new sheat or old one i cant add nay components.I treied to uninstall app and install it again and i have sam thing

**Comment by voltsimapp** [comment]
Hello @MrAresCro  Thank you for reporting the issue.  We already had a report of this issue through email from `Bojan Plesa`. Is this the same report?

**Comment by voltsimapp** [comment]
closing as we cannot reproduce and no response from the reporter.
