### ISSUE TITLE
Component Request

### ISSUE THREAD

**Issue by Awen2345** [VoltSim/VoltSim#2]
Please Add Components such as:
Mosfets
Zener,Schottky,
DIAC,
TRIAC,
Tunnel Diode
Voltage Controlled Source,
 Relay,
Optocoupler,
Logic Gates ,
 Spark Gap
Integrated Circuit
Etc ...

**Comment by voltsimapp** [comment]
New components are definitely on the TODO list. we will be publishing a detailed timeline of planned components soon.

**Comment by voltsimapp** [comment]
Relay, Digital gates, Bulb added. 
More in pipeline ...

**Comment by voltsimapp** [comment]
we have added zener diode, 555IC, mosfets in this update.
