### ISSUE TITLE
Insecure app content

### ISSUE THREAD

**Issue by damiandaminczyk** [VoltSim/VoltSim#22]
I found out that this app is insecure, database content can be easily cracked:

`{"voltage_range":5,"elements":[], <REDACTED>   "label_map":"{T=1}"}`

**Comment by voltsimapp** [comment]
Hi @damiandaminczyk , Thank you for reporting this. In a normal phone, the app database should be inaccessible to the user. Did you use a rooted phone to access the database?

**Comment by damiandaminczyk** [comment]
I have acces to database from APK, everything is in plain text. It should be encrypted.

**Comment by damiandaminczyk** [comment]
You can check below output from database:
`{"max_time_step":5.0E-6,"min_time_step":5.0E-11,"iteration_count":3.9121283998153213,"current_speed":55,"voltage_range":5,"elements":[{"name":"Wire","x":325,"y":600,"x2":325,"y2":700,"height":0,"label":"nullnull","flags":0,"uid":"97bc4eb0-28d2-4556-91f0-45ee0c14e51d","scoped_values":[],"blockingBBoxes":"{\"first\":{\"height\":101,\"width\":32,\"x\":309,\"y\":500},\"second\":{\"height\":32,\"width\":101,\"x\":225,\"y\":684}}","segmentPoints":"[]"},{"name":"Wire","x":250,"y":350,"x2":325,"y2":500,"height":0,"label":"nullnull","flags":0,"uid":"0381eeff-00e8-4d69-9bd7-eea4949f48fb","scoped_values":[],"blockingBBoxes":"{\"first\":{\"height\":32,\"width\":101,\"x\":150,\"y\":334},\"second\":{\"height\":101,\"width\":32,\"x\":309,\"y\":500}}","segmentPoints":"[{\"x\":325,\"y\":350}]"},{"name":"Wire","x":125,"y":350,"x2":150,"y2":350,"height":0,"label":"nullnull","flags":0,"uid":"122e1df6-a6ec-4ec1-972b-6d9fa2affefe","scoped_values":[],"blockingBBoxes":"{\"first\":{\"height\":4,\"width\":4,\"x\":123,\"y\":348},\"second\":{\"height\":32,\"width\":101,\"x\":150,\"y\":334}}","segmentPoints":"[]"},{"name":"Wire","x":125,"y":350,"x2":125,"y2":475,"height":0,"label":"nullnull","flags":0,"uid":"86b1248a-7089-462a-ad64-05de7c316ce8","scoped_values":[],"blockingBBoxes":"{\"first\":{\"height\":4,\"width\":4,\"x\":123,\"y\":348},\"second\":{\"height\":101,\"width\":16,\"x\":117,\"y\":475}}","segmentPoints":"[]"},{"name":"Wire","x":125,"y":575,"x2":125,"y2":700,"height":0,"label":"nullnull","flags":0,"uid":"55499c20-8ce6-4af4-9112-5fe10f1a35dd","scoped_values":[],"blockingBBoxes":"{\"first\":{\"height\":101,\"width\":16,\"x\":117,\"y\":475},\"second\":{\"height\":4,\"width\":4,\"x\":123,\"y\":698}}","segmentPoints":"[]"},{"name":"Wire","x":75,"y":350,"x2":125,"y2":350,"height":0,"label":"nullnull","flags":0,"uid":"3cd71f1d-f157-4236-b132-ebb9286ad2a3","scoped_values":[],"blockingBBoxes":"{\"first\":{\"height\":32,\"width\":101,\"x\":-25,\"y\":334},\"second\":{\"height\":4,\"width\":4,\"x\":123,\"y\":348}}","segmentPoints":"[]"},{"name":"Wire","x":75,"y":700,"x2":125,"y2":700,"height":0,"label":"nullnull","flags":0,"uid":"0cc732b6-881e-4fc8-bc30-5fd138046268","scoped_values":[],"blockingBBoxes":"{\"first\":{\"height\":24,\"width\":101,\"x\":-25,\"y\":688},\"second\":{\"height\":4,\"width\":4,\"x\":123,\"y\":698}}","segmentPoints":"[]"},{"name":"Wire","x":-25,"y":350,"x2":-25,"y2":700,"height":0,"label":"nullnull","flags":0,"uid":"bdb96223-d1d8-4e1c-9a92-7ba8f5bb2e86","scoped_values":[],"blockingBBoxes":"{\"first\":{\"height\":32,\"width\":101,\"x\":-25,\"y\":334},\"second\":{\"height\":24,\"width\":101,\"x\":-25,\"y\":688}}","segmentPoints":"[{\"x\":-69,\"y\":350},{\"x\":-69,\"y\":700}]"},{"name":"Text","x":-143,"y":285,"x2":428,"y2":286,"height":0,"label":"nullnull","flags":0,"uid":"35247836-c54b-472a-bb8b-c43715481ce1","scoped_values":[],"text":"Turn the switch on and then off to start the oscillation","fontsize":25},{"name":"Post","x":125,"y":350,"x2":125,"y2":350,"height":0,"label":"nullnull","flags":0,"uid":"cbadb417-ee7a-477e-bcea-212a1daeacb9","scoped_values":[]},{"name":"Resistor","x":-25,"y":350,"x2":75,"y2":350,"height":0,"label":"R3","flags":0,"uid":"5843a8d2-0320-4135-84ba-248f12e4c86b","scoped_values":[],"resistance":10},{"name":"Inductor","x":125,"y":475,"x2":125,"y2":575,"height":0,"label":"L1","flags":0,"uid":"2c50be6b-b815-4d43-9da4-52f065017a91","scoped_values":[0],"inductance":1},{"name":"Capacitor","x":-25,"y":700,"x2":75,"y2":700,"height":0,"label":"C2","flags":0,"uid":"f207bfdf-826d-447d-855c-632a71a31cba","scoped_values":[],"capacitance":1.4999999999999999E-5,"initialVoltage":0.001},{"name":"Resistor","x":225,"y":700,"x2":325,"y2":700,"height":0,"label":"R3","flags":0,"uid":"70cb204c-c81c-41a6-9789-b73631571bda","scoped_values":[],"resistance":100},{"name":"Post","x":125,"y":700,"x2":125,"y2":700,"height":0,"label":"nullnull","flags":0,"uid":"52b8baa3-a57f-4b98-971c-8d38e3fe3614","scoped_values":[]},{"name":"Wire","x":125,"y":700,"x2":225,"y2":700,"height":0,"label":"nullnull","flags":0,"uid":"3e8877aa-2f7b-4299-96d1-a3ef5f4fd353","scoped_values":[],"blockingBBoxes":"{\"first\":{\"height\":4,\"width\":4,\"x\":123,\"y\":698},\"second\":{\"height\":32,\"width\":101,\"x\":225,\"y\":684}}","segmentPoints":"[]"},{"name":"DCVoltage","x":325,"y":600,"x2":325,"y2":500,"height":0,"label":"V3","flags":0,"uid":"6e327913-2148-4d7a-be1c-42feae575a67","scoped_values":[],"waveform":0,"frequency":40,"maxVoltage":5,"bias":0,"phaseShift":0,"dutyCycle":0.5},{"name":"Switch","x":150,"y":350,"x2":250,"y2":350,"height":0,"label":"SWT2","flags":0,"uid":"3c776e45-b471-4b59-9546-516b1998d731","scoped_values":[],"position":1,"momentary":false}],"label_map":"{}"}`

**Comment by damiandaminczyk** [comment]
I can read also all types of comonents like output below, those strings should be hidden:
`return (b)(str.equals("GroundElm") ? new h(paramInt1, paramInt2) : (str.equals("ResistorElm") ? new f71(paramInt1, paramInt2) : (str.equals("CapacitorElm") ? new a(paramInt1, paramInt2) : (str.equals("PolarCapacitorElm") ? new rx0(paramInt1, paramInt2) : (str.equals("InductorElm") ? new j(paramInt1, paramInt2) : ((str.equals("DCVoltageElm") || str.equals("VoltageElm")) ? new hm(paramInt1, paramInt2) : (str.equals("ACVoltageElm") ? new d(paramInt1, paramInt2) : (str.equals("CurrentElm") ? new e(paramInt1, paramInt2) : (str.equals("NoiseSourceElm") ? new bs0(paramInt1, paramInt2) : (str.equals("PulseSourceElm") ? new u01(paramInt1, paramInt2) : (str.equals("SawtoothSourceElm") ? new ub1(paramInt1, paramInt2) : (str.equals("SquareSourceElm") ? new yi1(paramInt1, paramInt2) : (str.equals("TriangleSourceElm") ? new ct1(paramInt1, paramInt2) : (str.equals("SwitchElm") ? new nm1(paramInt1, paramInt2, false) : (str.equals("DiodeElm") ? new mq(paramInt1, paramInt2) : (str.equals("PostElm") ? new fy0(paramInt1, paramInt2) : (str.equals("LEDElm") ? new qg0(paramInt1, paramInt2) : (str.equals("NTransistorElm") ? new fq0(paramInt1, paramInt2) : (str.equals("PTransistorElm") ? new wv0(paramInt1, paramInt2) : (str.equals("PotElm") ? new gy0(paramInt1, paramInt2) : (str.equals("AmmeterElm") ? new n2(paramInt1, paramInt2) : (str.equals("VoltmeterElm") ? new u02(paramInt1, paramInt2) : (str.equals("PushSwitchElm") ? new y01(paramInt1, paramInt2) : (str.equals("SwitchSPDTElm") ? new om1(paramInt1, paramInt2) : (str.equals("TransformerElm") ? new rr1(paramInt1, paramInt2) : (str.equals("ACRailElm") ? new c(paramInt1, paramInt2) : (str.equals("RailElm") ? new m(paramInt1, paramInt2) : (str.equals("TextElm") ? new ro1(paramInt1, paramInt2) : (str.equals("ZenerDiodeElm") ? new u22(paramInt1, paramInt2) : (str.equals("FuseElm") ? new s40(paramInt1, paramInt2) : (str.equals("OpampElm") ? new lv0(paramInt1, paramInt2) : (str.equals("LogicGenElm") ? new ak0(paramInt1, paramInt2) : (str.equals("AndGateElm") ? new r2(paramInt1, paramInt2) : (str.equals("OrGateElm") ? new tv0(paramInt1, paramInt2) : (str.equals("XorGateElm") ? new p22(paramInt1, paramInt2) : (str.equals("XnorGateElm") ? new o22(paramInt1, paramInt2) : (str.equals("LogicOutElm") ? new bk0(paramInt1, paramInt2) : (str.equals("NandGateElm") ? new lq0(paramInt1, paramInt2) : (str.equals("NorGateElm") ? new gs0(paramInt1, paramInt2) : (str.equals("NotGateElm") ? new is0(paramInt1, paramInt2) : (str.equals("RelayElm") ? new b61(paramInt1, paramInt2) : (str.equals("BulbElm") ? new ta(paramInt1, paramInt2) : (str.equals("IC555Elm") ? new r90(paramInt1, paramInt2) : (str.equals("MosfetNElm") ? new hp0(paramInt1, paramInt2) : (str.equals("MosfetPElm") ? new ip0(paramInt1, paramInt2) : (str.equals("SparkGapElm") ? new ki1(paramInt1, paramInt2) : (str.equals("DCMotorElm") ? new gm(paramInt1, paramInt2) : (str.equals("TunnelDiodeElm") ? new ft1(paramInt1, paramInt2) : (str.equals("ADCElm") ? new e(paramInt1, paramInt2) : (str.equals("DFlipFlopElm") ? new im(paramInt1, paramInt2) : (str.equals("SchmittElm") ? new mc1(paramInt1, paramInt2, false) : (str.equals("InvertedSchmittElm") ? new kd0(paramInt1, paramInt2) : (str.equals("AMSourceElm") ? new f(paramInt1, paramInt2) : (str.equals("FMSourceElm") ? new bx(paramInt1, paramInt2) : (str.equals("LEDMatrixElm") ? new rg0(paramInt1, paramInt2) : (str.equals("SchottkyDiodeElm") ? new nc1(paramInt1, paramInt2) : (str.equals("AntennaElm") ? new k3(paramInt1, paramInt2) : (str.equals("TFlipFlopElm") ? new ym1(paramInt1, paramInt2) : (str.equals("SevenSegmentElm") ? new oe1(paramInt1, paramInt2) : (str.equals("SevenSegmentDecoderElm") ? new ne1(paramInt1, paramInt2) : (str.equals("BuzzerElm") ? new ya(paramInt1, paramInt2) : (str.equals("ProbeElm") ? new bz0(paramInt1, paramInt2) : (str.equals("WobbulatorElm") ? new v12(paramInt1, paramInt2) : (str.equals("OhmMeterElm") ? new zt0(paramInt1, paramInt2) : (str.equals("TransformerTappedElm") ? new sr1(paramInt1, paramInt2) : (str.equals("ThyristorElm") ? new cq1(paramInt1, paramInt2) : (str.equals("MultiplexerElm") ? new up0(paramInt1, paramInt2) : (str.equals("DeMultiplexerElm") ? new fn(paramInt1, paramInt2) : (str.equals("AdderElm") ? new r1(paramInt1, paramInt2) : (str.equals("JKFlipFlopElm") ? new ud0(paramInt1, paramInt2) : (str.equals("SequenceGeneratorElm") ? new ed1(paramInt1, paramInt2) : (str.equals("DiacElm") ? new up(paramInt1, paramInt2) : (str.equals("ClockElm") ? new if(paramInt1, paramInt2) : (str.equals("LDRElm") ? new pg0(paramInt1, paramInt2) : (str.equals("CounterElm") ? new fl(paramInt1, paramInt2) : (str.equals("SpeakerElm") ? new oi1(paramInt1, paramInt2) : null))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));`

**Comment by damiandaminczyk** [comment]
Please address those security issues in next version.

**Comment by voltsimapp** [comment]
Regarding the unobfuscated code. we have reduced the obfuscation level in this update, which might have caused this. We will increase the obfuscation in the next update.

Regarding the data in the database embedded in the app. We do not consider this a security risk. We have an option of exporting a project as JSON in the timeline. Which would let the user see all this info anyway.

**Comment by voltsimapp** [comment]
We have increased the obfuscation level back up in 0.2.0
