### ISSUE TITLE
Import netlist function

### ISSUE THREAD

**Issue by mh0520** [VoltSim/VoltSim#23]
Are there plans to add the ability to import netlist or schematic files from other editors, like kicad?

**Comment by voltsimapp** [comment]
@mh0520 Importing schematic from other editors is not in the pipeline yet. 
We would be focusing on improving the simulation speed and adding more components before moving on to more integrations.

**Comment by gsingh93** [comment]
What about exporting a netlist so I can take a design from the app and open it in something like KiCad, so I can add footprints and layout a PCB?

**Comment by voltsimapp** [comment]
This can be done, as internally the component parameters are similar. Currently, the app saves the circuits in json.  This is in the pipeline but not a high priority at the moment.

**Comment by voltsimapp** [comment]
Closing this as this is not a priority. Will reopen when we add this to our timeline again.
