### ISSUE TITLE
XNOR logic gate bugs

### ISSUE THREAD

**Issue by jacius** [VoltSim/VoltSim#24]
Using VoltSim 0.2.0 on Android 11, there are several bugs with the XNOR logic gate component.

1. When a new XNOR gate is added, it looks like a NOR gate (incorrect) but behaves like an XNOR gate (correct).
2. When the XNOR gate is selected, the MultiMeter window says it is an XOR gate (incorrect).
3. After the project is saved and reopened, the XNOR gate looks and behaves like an XOR gate (incorrect).

**Comment by voltsimapp** [comment]
@jacius  Thank you for raising these bug tickets. We are able to reproduce these bugs and will deploy fixed in our next update.

**Comment by voltsimapp** [comment]
Fixed in 0.2.1
