### ISSUE TITLE
Make logic gate appearances more distinct

### ISSUE THREAD

**Issue by jacius** [VoltSim/VoltSim#25]
I would like to request that the appearance of logic gates be improved so that it is easier to tell them apart. They look too similar to one another, especially when zoomed out.

My recommendations are:

1. The OR/NOR/XOR/XNOR gates should curve inward more on the input side, and have no flatness on the top or bottom (the curves should flow from the top/bottom corners to the tip).
2. The NOT/NAND/NOR/XNOR gates should have a larger circle at the output, about 2 or 2.5 times the current size.

See the image at the top of [this article](https://www.nutsvolts.com/magazine/article/small-logic-gates-spawn-big-dreams-part-1) for a great example of logic gate symbols that are clear and easy to tell apart.

**Comment by voltsimapp** [comment]
Fixed in 0.2.1, please reopen if issue still exists.
