### ISSUE TITLE
inverted mosfet symbol

### ISSUE THREAD

**Issue by Awen2345** [VoltSim/VoltSim#27]
![Screenshot_2022-12-02-19-02-10-55.jpg](https://user-images.githubusercontent.com/87870432/205288974-420e2c49-0e0a-4dcd-a49a-89d58f3b5327.jpg)
The one on the far left is an n channel mosfet but the symbol is like a p mosfet And secondly To the right of the p mosfet the symbol is like the n mosfet So I can't tell the difference between n mos and pmos

**Comment by Awen2345** [comment]
![Screenshot_2022-12-02-19-09-13-03.jpg](https://user-images.githubusercontent.com/87870432/205289825-894d453f-6ad3-42ca-a182-731988c807de.jpg)
This should be the correct symbol

**Comment by voltsimapp** [comment]
You can flip it to the correct position by the VFlip button in the bottom menu. 
Will update the default orientation in the next update.

**Comment by voltsimapp** [comment]
Fixed in 0.2.1, please reopen if the issue still exists.
