### ISSUE TITLE
Tema escuro

### ISSUE THREAD

**Issue by ProfetaDJ** [VoltSim/VoltSim#33]
Ícones na barra inferior do projeto ficam ocultos quando ativado o tema escuro do aparelho. 
Sugestão: Alterar cores dos ícones e/ou criar temas específicos.

**Comment by ProfetaDJ** [comment]
![Screenshot_2023-01-09-12-09-57-499_com fallenbug circuitsimulator](https://user-images.githubusercontent.com/122238134/211342183-a6a0d1ca-8d40-4357-9777-74c5972e9008.jpg)
![Screenshot_2023-01-09-12-10-48-513_com fallenbug circuitsimulator](https://user-images.githubusercontent.com/122238134/211342184-8069f6c1-ed61-4532-98b1-6e6af31a4dc7.jpg)
![Screenshot_2023-01-09-12-12-05-978_com android settings](https://user-images.githubusercontent.com/122238134/211342307-a1949a1f-a776-47ce-beec-96b3e71a2562.jpg)

**Comment by voltsimapp** [comment]
Thank you, we will fix this in the next release.
Obrigado, vamos corrigir isso no próximo lançamento.

**Comment by nithinmurali** [comment]
@ProfetaDJ  Você pode fornecer algumas etapas para reproduzir esse problema? Não podemos reproduzir isso do nosso lado.

Can you please provide some steps to reproduce this issue? We are unable to reproduce this on our end.

**Comment by voltsimapp** [comment]
@ProfetaDJ Você pode fornecer algumas etapas para reproduzir esse problema? Não podemos reproduzir isso do nosso lado.

Can you please provide some steps to reproduce this issue? We are unable to reproduce this on our end.

**Comment by voltsimapp** [comment]
We are unable to reproduce this and since there is no response from the reporter, we can closing this issue. Please feel free to reopen if you face this issue again.
