### ISSUE TITLE
Create PCB board 

### ISSUE THREAD

**Issue by taishingi** [VoltSim/VoltSim#34]
Design a PCB board with the schema and can  command it. 

Use Paypal for payment.

You can use JL PCB or other companies for components.

Send PCB via courier.

I hope it's validated.

**Comment by voltsimapp** [comment]
Hello, Thank you for reporting this. We focusing first on the simulation of components. We could add a circuit export feature which can then be opened on a software dedicated for PCB design.  

So closing this as this doesn't align with out future plan.

**Comment by taishingi** [comment]
ok thank
