### ISSUE TITLE
Append puissance électronique 

### ISSUE THREAD

**Issue by taishingi** [VoltSim/VoltSim#36]
Add puissance components.

**Comment by voltsimapp** [comment]
Can you please provide some supporting links explaining this component?

**Comment by taishingi** [comment]
https://en.wikipedia.org/wiki/Power_electronics?wprov=sfla1

**Comment by taishingi** [comment]
https://www.dunod.com/sites/default/files/atoms/files/9782100738663/Feuilletage.pdf

**Comment by Awen2345** [comment]
@taishingi is not Component!!!!

**Comment by taishingi** [comment]
Okay i'm sorry...
