### ISSUE TITLE
Bug bulb continue to gleam


### ISSUE THREAD

**Issue by taishingi** [VoltSim/VoltSim#39]
After opening the circuit by a switch before a bulb the bulb continues to gleam.

but the led  diode stops gleaming after opening the circuit 

![Screenshot_2023-01-29-00-09-51-060_com.fallenbug.circuitsimulator.jpg](https://user-images.githubusercontent.com/101449384/215295323-7bbf321c-fc3e-4ccd-9b33-c36942b696f4.jpg)

![Screenshot_2023-01-29-00-10-33-679_com.fallenbug.circuitsimulator.jpg](https://user-images.githubusercontent.com/101449384/215295335-e686240f-141a-4187-a5cd-f2684b1e99f1.jpg)

**Comment by voltsimapp** [comment]
Hi, 
the bulb will continue to glow as long as the temperature of the bulb is above a certain threshold. Once the switch is turned off you can see in the multimeter that the bulb temperature is coming down, so it will turn off after some time. If you want the bulb to turn off faster you can adjust the "time to cooldown" parameter in edit.

**Comment by taishingi** [comment]
Ok great 👍
