### ISSUE TITLE
Fix the app next update

### ISSUE THREAD

**Issue by Awen2345** [VoltSim/VoltSim#4]
1. Save Settings with projects
2. IC  missing after project opened
3. Centre Circuits after open projects
This is Bug in apk....

**Comment by Awen2345** [comment]
Uploading Record_2022-03-03-22-20-36.mp4…

IC 555 is missing after saving project and open projects

**Comment by Awen2345** [comment]
Uploading Record_2022-03-03-22-20-36.mp4…
IC 555 is missing after open saved projects

**Comment by voltsimapp** [comment]
Hi, Thanks for reporting the bug. 

1. can you explain this please. Do you mean that the setting like "show voltage", "grid setting" etc should be saved for each project?

2. Are you facing this for all the projects with an IC?

3.The circuit should automatically center once project is loaded. Are you seeing this issue for all the projects?

**Comment by voltsimapp** [comment]
Hello @Awen2345 , can you please send a screenshot of the circuit where the IC 555 is missing after saving and opening project, please?

**Comment by Awen2345** [comment]
![Screenshot_2022-03-14-20-49-26-96.jpg](https://user-images.githubusercontent.com/87870432/158188848-ae286c78-9758-4038-8550-f4b66302187c.jpg)

Before

**Comment by Awen2345** [comment]
![Screenshot_2022-03-14-20-49-50-88.jpg](https://user-images.githubusercontent.com/87870432/158188907-94b4ed7b-b3ee-4a90-8a1d-d7410d1c0fcf.jpg)

**Comment by Awen2345** [comment]
![Screenshot_2022-03-14-20-49-43-19.jpg](https://user-images.githubusercontent.com/87870432/158188972-9de7f764-3680-472d-ab43-318238435032.jpg)
After I reopened My projects

**Comment by nithinmurali** [comment]
thanks @Awen2345 , We will fix this in the next update.

**Comment by voltsimapp** [comment]
We have a new update released which fixed all these issues reported.

**Comment by voltsimapp** [comment]
if the issue persists, please reopen
