### ISSUE TITLE
Leds only appear in one color at a time

### ISSUE THREAD

**Issue by tejprn** [VoltSim/VoltSim#42]
This issue is specific to my phone(android). I tried on 2 other phones where the app is working as intended.

Issue: When adding multiple Leds of different colors in a circuit, only one (the one which is last tapped/selected) color shows up for all leds in the circuit. This is true for the entire project even if the leds are on separate unconnected circuits.

**Comment by tejprn** [comment]
My Phone details:
![Screenshot_20230531_205712](https://github.com/VoltSim/VoltSim/assets/22633744/ff1740d4-436e-4f87-8b0d-da915fef0d69)

**Comment by voltsimapp** [comment]
Thank you for reporting! We had some other reports of this same issue. Marked as a bug, will look into it.

**Comment by voltsimapp** [comment]
Is this happening on a specific project or is it happening on all the projects on your phone? Can you please share the project? (using the shared button)

**Comment by tejprn** [comment]
Sorry for the late response here. Yes, it's happening with all the projects. Sharing an example.
Project 1
Once all leds are connected by switching on, the color appears based on which led is tapped last. Touching any 1 led will make all other leds of the same color. However when checked using edit the original color shows correctly inside the edit function.

**Comment by voltsimapp** [comment]
Unfortunately, we cannot replicate this in any of the test devices we have tried. So we will keep this as a won't fix for now. If there are more user reports of the same issue, we will look into this.
