### ISSUE TITLE
Antenna is working on only 5v it is not variable

### ISSUE THREAD

**Issue by maheshvk181** [VoltSim/VoltSim#43]
Antenna is working on only 5v it is not variable

**Comment by voltsimapp** [comment]
Hello, are you trying to change the antenna max voltage? Currently, the max voltage can be up to 20V.  Are you trying to make this variable?

**Comment by maheshvk181** [comment]
yes ,it showing Vmax=5V after changing the voltage to 20V

**Comment by voltsimapp** [comment]
Please plot the antenna output in scope and send a screenshot here.

**Comment by maheshvk181** [comment]
Yes we cant vary voltage of antena always its its showing the Vmax=5V.

**Comment by voltsimapp** [comment]
Will add an option for changing the Antena Max voltage in the next update. should be a simple fix.

**Comment by voltsimapp** [comment]
We have released this feature in 0.2.8
