### ISSUE TITLE
Add more components

### ISSUE THREAD

**Issue by srantheman** [VoltSim/VoltSim#47]
Can Add more components stabilitron

**Comment by voltsimapp** [comment]
This is the same as zener diode as specified in the other issue

**Comment by srantheman** [comment]
You realy it all good can make ciruit inpulse using my components

2023-11-23, kt 17:57, voltsimapp ***@***.***> rašė:

**Comment by voltsimapp** [comment]
Please checkout the latest update. If that doesn't solve the issue please create a new GitHub issue.
