### ISSUE TITLE
A component that won't load..

### ISSUE THREAD

**Issue by desmo138** [VoltSim/VoltSim#50]
In the others tab in the add component section, the IC I believe it's an h-bridge will not load or add to project.. please fix if you can.. 
 I use the 555 all the time that in the same section..and I just got to have an h-bridge IC.. 
And by the way love your App..

**Comment by voltsimapp** [comment]
Hello, thanks for notifying us. Yes, that is an H-bridge, looks like there is an issue in our production build. We will fix it soon. Thanks
