### ISSUE TITLE
Inductive voltage spike not correctly simulated

### ISSUE THREAD

**Issue by MaelR691** [VoltSim/VoltSim#53]
Inductive voltage spike produced by inductors/relay coil is incorrectly simulated or not simulated at all. Using inductor and a simple pushbutton should produce a voltage spike when switch change state from closed to open according to V = L×(di/dt). Adjustable switch opening time (which could be avaukable to be set in switch settings) would complete the equation and simulate the spike. You could also add such "opening time" to transistors so spike would also be simulated using them.

**Comment by voltsimapp** [comment]
Hello, you can see the inductive kickback happening in this circuits https://www.voltsimulator.com/dl?id=hjpSrPCwOV5L9iTI9Qb1 

In voltsim the switches are modeled as Ideal switches, so they wont breakdown and conduct on high voltages. Hence the inductive kickback wont happen. 
If you would like to model a switch that breaks down, please add a "spark gap" in parallel to the switch and you can see the inductive kickback happening.
