### ISSUE TITLE
Random placement of new components 

### ISSUE THREAD

**Issue by cartesio88** [VoltSim/VoltSim#6]
When adding a new component to the circuit, it is placed randomly in the circuit. This makes it difficult to find them, since sometimes they overlap with other circuits, and if the oscilloscope view is open, it might be behind it. It would be useful to have them placed in a more predictable manner, like in the first empty space starting fromt top left corner

**Comment by voltsimapp** [comment]
Hi @cartesio88 , Thank you for raising this. we will make it more predictable.

**Comment by nithinmurali** [comment]
fixed in 0.1.20
