### ISSUE TITLE
Please add DPDT switch.

### ISSUE THREAD

**Issue by derei** [VoltSim/VoltSim#61]
I had to make a circuit with a DPDT switch, and the only option I had, was to customize a relay, as the only solution.

**Comment by voltsimapp** [comment]
Hi, this feature is already developed. You can expect this in the next release.

**Comment by derei** [comment]
Quick follow-up on this request: I understand major updates take time, but incorporating essential components like the DPDT switch could significantly enhance usability, especially for educational purposes.
Recently, I've been teaching students about DC motor polarity reversing. Simulating a DPDT switch using two SPDT switches has been somewhat confusing for them. Adding a few basic components, such as the DPDT switch, in a smaller patch release would be incredibly helpful.

Thanks for considering this, looking forward to any potential updates!

**Comment by voltsimapp** [comment]
Hello @derei , 
Thank you for bringing this to our attention. We understand the importance of incorporating features like the DPDT switch, especially for educational purposes, and we appreciate your patience as we were working on a major update.

As requested, we will have a small release in two weeks with the DPDT switch and a few other minor updates.

**Comment by voltsimapp** [comment]
In this release, we have added the DPDT switch as a new component and have also added grouping for controlling multiple SPST switches together.
