### ISSUE TITLE
Feature Suggestion: DC/AC power supply EMI noise

### ISSUE THREAD

**Issue by troydm** [VoltSim/VoltSim#66]
Would be nice to have a DC/AC power supply random EMI noise option feature with  ability to specify amplitude in milli volts and frequency in hertz so that we could simulate real life situations with noisy power supply, would help greatly, thanks

**Comment by voltsimapp** [comment]
you can simulate such a source by adding noise to ac source.

![emi-source](https://github.com/VoltSim/VoltSim/assets/94251430/9f0f21e5-c3a8-43f3-aa1c-2500cb618cf4)

**Comment by troydm** [comment]
@voltsimapp thank you
