### ISSUE TITLE
VCVS returns to default value

### ISSUE THREAD

**Issue by Geitinisveitinni** [VoltSim/VoltSim#67]
VCVS returns to default value if you close and reopen a project or use the undo button

**Comment by voltsimapp** [comment]
Hello, can you please provide the steps to reproduce this issue? Some screenshots or screen recording would be helpful as well.

**Comment by voltsimapp** [comment]
Thank you for the video and for sharing the project. Unfortunately it's still not clear to me what is not getting saved. The equation before and after saving is the same "5*(a-b)"  ?

**Comment by Geitinisveitinni** [comment]
Yes but the voltage and current values everywhere in the circuit are wrong until I press edit and save

**Comment by voltsimapp** [comment]
Thank you for reporting this bug! We will fix this in the next release.

**Comment by voltsimapp** [comment]
Fixed in 0.2.13 ; Please reopen if issue still persists
