### ISSUE TITLE
Scope trace display

### ISSUE THREAD

**Issue by ct1igu** [VoltSim/VoltSim#68]
Hi,

I think VoltSim has recently been updated. My installed version is 0.2.12.

I used to be able to go to 'Large Display' when tracing up to 4 inputs/outputs to see the four signals in separate traces. This was extremely useful but no longer seems to be working. All I get is a large version of the mixed signals.

I've attached an image of how it used to be.

Is there a way of getting back to the multi-display.

Many thanks for any help.

Rod
![Floyd Exp 4 - Voltsim - Trace 1](https://github.com/VoltSim/VoltSim/assets/151851188/c4cf5507-ae0e-49ae-abcf-aa36126db442)

**Comment by voltsimapp** [comment]
Hello, in the last update we have refined our scope preferences and added gestures. So you can just swipe down on the scope to split the channels into multiple traces. If this is not working make sure  H-swipe option is enabled in scope preferences. 

![WhatsApp Image 2024-04-26 at 8 22 02 AM(1)](https://github.com/VoltSim/VoltSim/assets/94251430/35d9d59f-ef91-4ad4-bcf4-d5cc496124af)
![WhatsApp Image 2024-04-26 at 8 22 02 AM](https://github.com/VoltSim/VoltSim/assets/94251430/a44a55c8-eb61-4997-bf5c-69d5fd35d7eb)
