### ISSUE TITLE
Can't change JFET Vp parameter

### ISSUE THREAD

**Issue by FelipeFatecSP** [VoltSim/VoltSim#69]
I found a bug, isn't possible to change JFET Vp. Add too the possibility to change IDSS (maximum drain current). Vp and IDSS is the most important parameters of JFETs (N and P Channel) and MOSFETS (N and P Channel), then check If Vp and IDSS from MOSFETs are changeable too. Thanks.
I paid for the app and I am a Electronic student.

**Comment by voltsimapp** [comment]
Hello, We have not yet implemented advanced editing for Mosfet and JFets. We will add it in our next update.

**Comment by voltsimapp** [comment]
Hello, In the latest update (0.2.14) , you can change Vgs(off) for FETs which is -Vp. Please reopen is this is not resolved.
