### ISSUE TITLE
Add positive voltage regulator (lm78** family)

### ISSUE THREAD

**Issue by abdullahmuslim** [VoltSim/VoltSim#71]
I got the app today, and must admit is amazing. I notice some components I would like to use are not yet in the app so I figured I should raise an issue.
The lm78** are sets of IC whose last two digits 
(starred) denote their output voltage. They work with DC voltage and are very handy in most converter circuit.
I hope this gets attention soon 🤗

**Comment by voltsimapp** [comment]
Adding more voltage regulators is a feature we have in the pipeline. Will keep this ticket updated.

**Comment by voltsimapp** [comment]
Hello, we have added LM7805 family in the latest update (0.2.14).
