### ISSUE TITLE
Make crystal component frequency configurable

### ISSUE THREAD

**Issue by chmosiii** [VoltSim/VoltSim#83]
New User : I like the app, however something doesn't seem to work ..

I paid on Sept/04/24 for the scope extension. The scope got updated as intended and parts in the parts library that were blocked got enabled too which I didn't expect to happen. However many parts are only symbols and cannot be simulated yet at the moment.

A few days later, seeing that there is another green payment button or link for an EXTENSION on the dashboard from where we load our projects, I clicked on it thinking that there was anoher library I could buy, but nothing happened, although my payment went through. No extra parts received .. nothing !!

I thought maybe since all the parts in my library were already enabled and complete on my first purchase, this extra link I clicked should have been grayed, or disabled so people don't click on it mistakenly since it doesn't do nothing.

Regard !!!

**Comment by voltsimapp** [comment]
Hi, all the components are simulated. If you have purchased the "Pack extension" [the $12.64 one]. All the features should be unblocked and all components should work.
Can you please share a screen recording of the components/parts not working?
Can you also please share your purchase id from google play? we will check for any permission issues there.

**Comment by chmosiii** [comment]
Hello,

I guess I'm in trouble. When I clicked the payment links, my PayPal link opened and I accepted to make the two payments (The Instrument Extension & The Extension Pack). However the payment was made outside Google Play Store, therefore VoltSim doesn't appear nowhere on my Play Store purchases area. I then checked the email I registered on your site, no bill there either. I then checked on my PayPal account, again here nothing shows I made a purchase on Voltsim althoughI paid through paypal. The scope was updated as I mentioned previously and the grayed parts as well, but dome are not simulable.

Speaking of the parts I can't simulate, one of them is the CRYSTAL. When I click to edit the frequency I want it to oscillate, all I see is the label and nothing else. I can't tell it to the frequency I want it to oscillate through the EDIT area. I drew a simple crystal oscillator, it does oscillate, but very erratically and nowhere I can't Edit the frequency of oscillation. As I said, when I click the Edit button, all I see is the crystal label and nothing else. There are other parts that aren't simulable, such as  the OpampReal I only see the label and cannot edit amps parameter in it.

As I mentioned above, I purchased the Instrument Extension that worked fine and that enabled all the grayed parts, and today the Extension Pack ($10.99).

I dont mind if I lost the $10.99 Extension Pack payment providing it passed, I just want to be able to simulate the parts.

Best regards ..

**Comment by voltsimapp** [comment]
Hi, Looks like the extension pack is active. 

Unfortunately, you cannot edit the frequency of the crystal oscillator. We will add a feature request for this and will fix this in the next update.

The Opamp-real is internally IC741 so its parameters cannot be changed as it matches that of 741. you will be able to change this model in future releases.
If you want to use an Opamp whose parameters can be changed, please use Opamp (Ideal) [The Opamp without rails]. There you should be able to update gain and rail voltages.

Let us know if you are missing any other parameters for simulation.

**Comment by chmosiii** [comment]
Ok great !! 

Now I understand ..

Regard ..

**Comment by voltsimapp** [comment]
Ability to configure crystal frequency added in 0.2.16
