### ISSUE TITLE
Remove all components from oscilloscope at once 

### ISSUE THREAD

**Issue by cartesio88** [VoltSim/VoltSim#9]
When you have selected several components to plot in the oscilloscope, sometimes you just want to take them all out and start with a clean plot, but you have to find every individual component to take it out of the plot. It would be nice to have a button to remove all the inputs at once from the oscilloscope

**Comment by nithinmurali** [comment]
Implemented in 0.1.11, currently its bundled with `Instruments extension` but will be moved out in next release.
